- name: Install Pip package
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker
  ansible.builtin.import_tasks:
    file: docker.yml

- name: Install Ansible Docker prerequisite
  become: true
  ansible.builtin.pip:
    name: docker

- name: Create Docker network
  become: true
  community.docker.docker_network:
    name: docker-network
    driver_options:
      com.docker.network.bridge.default_bridge: true
      com.docker.network.bridge.enable_icc: true
      com.docker.network.bridge.enable_ip_masquerade: true
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
      # com.docker.network.bridge.name: docker1
      com.docker.network.bridge.mtu: 1500
