- name: Create Nginx Folder
  ansible.builtin.file:
    path: "{{ nginx_folder }}"
    state: directory

- name: Create TLS Folder
  ansible.builtin.file:
    path: "{{ nginx_tls_folder }}"
    state: directory

- name: Copy Nginx Config to host
  ansible.builtin.template:
    src: nginx.conf.tpl
    dest: "{{ config_file }}"
  register: nginx_config_status

- name: Docker Tasks
  become: true
  block:
    - name: Launch Nginx Server
      community.docker.docker_container:
        # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
        name: nginx
        image: "{{ docker.nginx_image }}:{{ docker.nginx_version }}"
        published_ports:
          - 0.0.0.0:80:80
          - 0.0.0.0:443:443
        networks:
          - name: "{{ docker.network_name }}"
        # healthcheck:
        # command:
        #   - sleep
        #   - 999999
        volumes:
          - "{{ config_file }}:/etc/nginx/nginx.conf:ro"
          - "{{ nginx_tls_folder }}:/etc/nginx/tls:ro"
        restart_policy: unless-stopped
        restart: "{% if nginx_config_status.changed %}true{% else %}false{% endif %}"
        state: started
